### ISSUE TITLE
Get stuck after 10 epochs

### ISSUE THREAD

**Issue by seki-x** [minerva-ml/open-solution-cdiscount-starter#7]
According to the readme, run the command
```source run_neptune_command.sh```
after 10 epochs, about 1.5 hours, it gets stuck.
And stdout stops at
```
1629.251008,"
 1/79 [..............................] - ETA: 259s
 2/79 [..............................] - ETA: 152s
 3/79 
...
75/79 [===========================>..] - ETA: 2s
76/79 [===========================>..] - ETA: 2s
77/79 [============================>.] - ETA: 1s
78/79 [============================>.] - ETA: 0s
79/79 [==============================] - 52s
"
```
Is it at a predicting process?
If it is predicting, how long will it take?
At kaggle others also found this problem:
https://www.kaggle.com/c/cdiscount-image-classification-challenge/discussion/41478
Seems like someone getting stuck for at least for nearly 4 hours.

**Comment by ymcdull** [comment]
I guess the reason may be GPU out of memory, cause when I use "sampling" when doing predicting, I met some issue like "ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[1280,64,87,87]". Haven't found the solution yet.

**Comment by kamil-kaczmarek** [comment]
Hi @john7farrell,
check your output folder -> prediction indeed takes some time. Let me know if you see your data there.
Also, please check the status of your neptune job.

**Comment by seki-x** [comment]
Hi~@kamil-kaczmarek thanks for the reply!

Sorry I ran starter_100_100 for 4 hours and aborted it for no responses. 
(experiment ID 82e79711-9625-4722-8d17-b513cf525b32)

Roughly checked predict part of source code in [```models.py```](https://github.com/deepsense-ai/cdiscount-starter/blob/master/models.py)
```predictions = self.model.predict_generator(test_flow, test_steps, verbose=1)```
I guess it shouldn't give no responses in the stdout while predicting.

And recently I modify ```experiment_config.yaml``` to a large version
```
project-key: CDIS
name: starter_5270_2000

properties:
  - key: top_categories
    value: 5270
  - key: images_per_category
    value: 2000
  - key: epochs
    value: 1
  - key: pipeline_name
    value: InceptionPipeline
```
It crashed after running after 9 hours
for ```Killed: Out of memory```
(experiment ID 7659eac6-00b1-47c9-becf-9a95a33cef2e)
Is there anything wrong in this config ?

**Comment by kamil-kaczmarek** [comment]
Hi @john7farrell,

1. First of all, please update your code, since we have introduced some changes very recently.
2. Prediction step takes some time, thus please be patient. You can monitor your job online via [neptune.ml](https://neptune.ml/) page.
3. In principle you are right: with `verbose=1`, you should be able to see the Progbar.
4. Your config is fine ;-)
5. Error `Killed: Out of memory` means that you ran out of RAM. Maybe you have data leak and it is being cumulated in memory?

I will take a look at your jobs and get back with more details later.

Please send me entire link to your experiments.

Best,
Kamil

**Comment by kamil-kaczmarek** [comment]
@john7farrell I checked your jobs. What I wrote in the previous comment holds.

Note that on Neptune page you have [Compute Resources](https://neptune.ml/pricing/) section, where you can check how much memory you have.

Hope that helps,
Kamil

**Comment by seki-x** [comment]
@kamil-kaczmarek I ran the starter_100_100 and it suceeded after 2h39min,
also there're output files in output folder.
Except one small bug below (guess will be fixed soon :)
```
$ source run_neptune_command.sh
validation.invalid
 --- All found errors ---
["Value '100' is not of type 'str'. Path: '/properties/0/value'", "Value '100' is not of type 'str'. Path: '/properties/1/value'", "Value '1' is not of type 'str'. Path: '/properties/2/value'"]
Errors found but will not raise exception...
The provided job configuration /home/john/neptune/cdiscount-starter/experiment_config.yaml is invalid! Validation errors: 1. Value '100' is not of type 'str'. Path: '/properties/0/value'
, 2. Value '100' is not of type 'str'. Path: '/properties/1/value'
, 3. Value '1' is not of type 'str'. Path: '/properties/2/value'
```
and after change ```Value: 100``` to ```Value: '100'``` in the ```yaml``` file it worked.
Anyway, I think this issue can be closed now~
Thank you~

**Comment by kamil-kaczmarek** [comment]
Hi @john7farrell,

I am glad to hear that your experiment succeeded.

Quick note about your error: the latest pull request solved that. Make also sure, that you are using the latest `neptune-cli` that is `2.4.x`.

Best,
KK
